services:
  app:
    build: .
    container_name: bite_de_task
    command: python main.py
    volumes:
      - .:/bite_DE_task
      - .:/bite_DE_task/output
      - YOUR_DIRECTORY:/bite_DE_task/data
    networks:
      mynetwork:

  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: githubpr
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      mynetwork:


volumes:
    db:
networks:
  mynetwork:
    driver: bridge
    name: mynetwork