version: '3'

services:
  my_app:
    image: bite_de_task:latest
    # Replace 'your_app_image:latest' with the name of your application's Docker image.

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghdatawh
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
